Update publish_pages.yml

diff --git a/.github/workflows/publish_pages.yml b/.github/workflows/publish_pages.yml
--- a/.github/workflows/publish_pages.yml
+++ b/.github/workflows/publish_pages.yml
@@ -6,6 +6,7 @@ on:
       # NOTE: You may want to limit the trigger branch to be "main" or "master" etc.
       - master
 
+# based on https://github.com/ammaraskar/sphinx-action-test/blob/master/.github/workflows/default.yml
 jobs:
   publish:
     runs-on: ubuntu-latest
@@ -14,20 +15,30 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Generate website
-        run: make -C docs/ html
-
-      - name: Publish current workdir (which contains generated content) to GitHub Pages
-        uses: rayluo/github-pages-overwriter@v1.1
-
+        uses: ammaraskar/sphinx-action@master
         with:
+          build-command: "make -C docs/ html"
+          docs-folder: "docs/"
+      - uses: actions/upload-artifact@v1
+        with:
+          name: DocumentationHTML
+          path: docs/_build/html/
 
-          # Optional. Default value "." means the root directory of your project will be published.
-          # You can use whatever directory your project uses, for example "wwwroot".
-          # Such a directory does *not* have to already exist in your repo,
-          # it could be an output directory created dynamically by your static website builder.
-          source-directory: ./docs/_build/html
-
-          # Optional. Default value "gh_pages".
-          # It specifies the temporary branch which hosts the static website.
-          # Each build will OVERWRITE this branch.
-          target-branch: gh_pages
+      - name: Commit documentation changes
+        run: |
+          git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
+          cp -r docs/_build/html/* gh-pages/
+          cd gh-pages
+          touch .nojekyll
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add .
+          git commit -m "Update documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # that.
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          directory: gh-pages
+          github_token: ${{ secrets.GITHUB_TOKEN }}
